CREATE TABLE `amzn_product` (
  `sku` varchar(48) NOT NULL DEFAULT '',
  `asin` varchar(10) DEFAULT NULL,
  `upc` varchar(12) DEFAULT NULL,
  `name` varchar(300) DEFAULT NULL,
  `size` varchar(10) DEFAULT NULL,
  `color` varchar(10) DEFAULT NULL,
  `disp_order` int DEFAULT '0',
  `group_id` varchar(11) DEFAULT NULL,
  `group_name` varchar(200) DEFAULT NULL,
  `product_type` varchar(10) DEFAULT NULL,
  `image_path` varchar(100) DEFAULT NULL,
  `group_name_short` varchar(50) DEFAULT NULL,
  `parent_name` varchar(50) DEFAULT NULL,
  `market` char(2) NOT NULL DEFAULT 'CA',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `production_cost` decimal(11,2) NOT NULL DEFAULT '0.00',
  `shipping_cost` decimal(11,2) NOT NULL DEFAULT '0.00',
  `price` decimal(11,2) NOT NULL DEFAULT '0.00',
  `weight` float DEFAULT '0',
  PRIMARY KEY (`sku`),
  KEY `idx_group_id` (`group_id`),
  KEY `idx_product_type` (`product_type`),
  KEY `idx_group_name` (`group_name_short`)
)

CREATE TABLE `amzn_scan_batch` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `market` char(2) NOT NULL DEFAULT 'CA',
  `scan_date` datetime DEFAULT CURRENT_TIMESTAMP,
  `ship_flag` tinyint DEFAULT '0',
  `shipment_id` varchar(200) DEFAULT NULL,
  `user` varchar(100) DEFAULT NULL,
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP,
  `batch_name` varchar(100) DEFAULT NULL,
  `pick_file_generate_count` smallint DEFAULT '0',
  `pack_file_generate_count` smallint DEFAULT '0',
  `close_flag` tinyint DEFAULT '0',
  `shipment_plan` json DEFAULT NULL,
  `create_user` varchar(100) DEFAULT NULL,
  `update_user` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_scan_date` (`scan_date`)
)

CREATE TABLE `amzn_scanned_products` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `scan_id` int unsigned DEFAULT '0',
  `box_num` int DEFAULT '0',
  `box_type` varchar(5) DEFAULT NULL,
  `market` char(2) NOT NULL DEFAULT 'CA',
  `scan_date` datetime DEFAULT CURRENT_TIMESTAMP,
  `sku` varchar(48) DEFAULT NULL,
  `upc` varchar(12) DEFAULT NULL,
  `asin` varchar(20) DEFAULT NULL,
  `name` varchar(300) DEFAULT NULL,
  `quantity` int DEFAULT '0',
  `ship_flag` tinyint DEFAULT '0',
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP,
  `create_user` varchar(100) DEFAULT NULL,
  `update_user` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_scan_date` (`scan_date`),
  KEY `idx_upc` (`upc`),
  KEY `idx_asin` (`asin`)
)